// Generated by IcedCoffeeScript 1.4.0b
(function() {
  var parse_L;

  window.parse_L = parse_L = function(root, termIdP) {
    var days, i, items, tables, ymd, _i, _len, _results;
    days = root.find('td.doc_title').map(function() {
      var match, md;
      if ((match = /(\d+)月(\d+)日/.exec(this.innerHTML)) == null) {
        throw Error(this.innerHTML);
      }
      return md = inferYear(termIdP, parseInt(match[1]), parseInt(match[2]));
    });
    tables = root.find('> table.data_list_table');
    _results = [];
    for (i = _i = 0, _len = days.length; _i < _len; i = ++_i) {
      ymd = days[i];
      items = $(tables[i]).find('tr:not(.data_list_title)').map(function() {
        var fields;
        fields = $(this).find('td').map(function() {
          return this.innerHTML;
        });
        return {
          beginT: getTOffset(moment(fields[0], 'HHmm')),
          endT: getTOffset(moment(fields[1], 'HHmm')),
          name: fields[3],
          loc: fields[4]
        };
      });
      _results.push({
        ymd: ymd,
        items: items
      });
    }
    return _results;
  };

}).call(this);
